
name: Build Docker R2 Image and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image for amd64
        run: |
          docker buildx build --platform linux/amd64 -t r2:amd64 --load .
      
      - name: Build the Docker image for arm64
        run: |
          docker buildx build --platform linux/arm64 -t r2:arm64 --load .
      
      - name: Save Docker image as tar for amd64
        run: |
          docker save r2:amd64 -o r2_amd64.tar
      
      - name: Save Docker image as tar for arm64
        run: |
          docker save r2:arm64 -o r2_arm64.tar
      
      - name: Upload Docker image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: r2_images
          path: |
            r2_amd64.tar
            r2_arm64.tar
